# Generated by Django 5.2.17 on 2026-10-02 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('asset_class', models.CharField(choices=[('EQUITY', 'Equity'), ('FX', 'FX'), ('CRYPTO', 'Crypto'), ('DEBT', 'Debt')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=100)),
                ('price', models.DecimalField(decimal_places=6, max_digits=100)),
                ('executed_at', models.DateTimeField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trades.instrument')),
            ],
        ),
    ]
